name: Beta Release

on:
  push:
    branches:
      - beta

env:
  REGISTRY: git.mrmave.work
  IMAGE_NAME: maverick/mavewaf
  CARGO_TERM_COLOR: always

jobs:
  build-binary:
    name: Build Signed Binary (Beta)
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    outputs:
      binary_sha256: ${{ steps.hash.outputs.sha256 }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang pkg-config libssl-dev musl-tools musl-dev gnupg

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          . "$HOME/.cargo/env"
          rustup target add x86_64-unknown-linux-musl
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build Release Binary
        env:
          CC: musl-gcc
          CXX: g++
          CC_x86_64_unknown_linux_musl: musl-gcc
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/mavewaf
          mv target/x86_64-unknown-linux-musl/release/mavewaf mavewaf-beta-linux-amd64

      - name: Generate SHA256
        id: hash
        run: |
          sha256sum mavewaf-beta-linux-amd64 > mavewaf-beta-linux-amd64.sha256
          echo "sha256=$(cat mavewaf-beta-linux-amd64.sha256)" >> $GITHUB_OUTPUT

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
            --detach-sign --armor mavewaf-beta-linux-amd64

      - name: Upload Binary Artifacts
        uses: https://code.forgejo.org/actions/upload-artifact@v3
        with:
          name: release-binaries
          path: |
            mavewaf-beta-linux-amd64
            mavewaf-beta-linux-amd64.sha256
            mavewaf-beta-linux-amd64.asc
          retention-days: 1

  test:
    name: Verify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang pkg-config libssl-dev

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: cargo test --verbose

  docker:
    name: Build Docker (Beta)
    runs-on: ubuntu-latest
    needs: build-binary
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download Binary Artifacts
        uses: https://code.forgejo.org/actions/download-artifact@v3
        with:
          name: release-binaries
          path: ./release-binaries

      - name: Setup Buildx
        uses: https://code.forgejo.org/docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: https://code.forgejo.org/docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: https://code.forgejo.org/docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=beta,enable=true

      - name: Build and Push
        id: build
        uses: https://code.forgejo.org/docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Cosign
        run: |
          curl -sLO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Sign Container Image
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_KEY" > /tmp/cosign.key
          cosign sign --yes --use-signing-config=false --key /tmp/cosign.key \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}
          rm /tmp/cosign.key
