name: Continuous Integration

on:
  push:
    branches:
      - master

env:
  REGISTRY: git.mrmave.work
  IMAGE_NAME: maverick/mavewaf
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang pkg-config libssl-dev jq

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --component clippy,rustfmt,llvm-tools-preview
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Coverage Tools
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Run Tests
        run: cargo llvm-cov --json --output-path coverage.json

      - name: Generate Badge
        run: |
          COVERAGE=$(jq -r '.data[0].totals.lines.percent' coverage.json)
          PERCENT=${COVERAGE%.*}
          if [ "$PERCENT" -ge 90 ]; then COLOR="brightgreen";
          elif [ "$PERCENT" -ge 75 ]; then COLOR="yellow";
          else COLOR="red"; fi
          curl -s -o coverage.svg "https://img.shields.io/badge/coverage-${PERCENT}%25-${COLOR}"

      - name: Upload Artifact
        uses: https://code.forgejo.org/actions/upload-artifact@v7
        with:
          name: coverage-badge
          path: coverage.svg
          retention-days: 1

      - name: Run Clippy
        run: cargo clippy -- -W clippy::pedantic -W clippy::nursery -D warnings

  badge:
    name: Update Badge
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: https://code.forgejo.org/actions/download-artifact@v7
        with:
          name: coverage-badge

      - name: Push to Branch
        run: |
          git config --global user.name "MaveWAF CI"
          git config --global user.email "ci@mrmave.work"
          git clone --branch badges https://oauth2:${{ secrets.GITHUB_TOKEN }}@git.mrmave.work/${{ github.repository }} badge_repo || \
            git clone https://oauth2:${{ secrets.GITHUB_TOKEN }}@git.mrmave.work/${{ github.repository }} badge_repo
          cd badge_repo
          if ! git show-ref --verify --quiet refs/heads/badges; then
             git checkout --orphan badges
             git rm -rf .
          fi
          cp ../coverage.svg .
          git add coverage.svg
          if git commit -m "Update coverage badge [skip ci]"; then
            git push origin badges
          fi